// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default (req, res) => {
  res.statusCode = 200
  res.json({
    id: 218115303,
    node_id: 'MDEwOlJlcG9zaXRvcnkyMTgxMTUzMDM=',
    name: 'swr',
    full_name: 'vercel/swr',
    private: false,
    owner: {
      login: 'vercel',
      id: 14985020,
      node_id: 'MDEyOk9yZ2FuaXphdGlvbjE0OTg1MDIw',
      avatar_url: 'https://avatars0.githubusercontent.com/u/14985020?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/vercel',
      html_url: 'https://github.com/vercel',
      followers_url: 'https://api.github.com/users/vercel/followers',
      following_url:
        'https://api.github.com/users/vercel/following{/other_user}',
      gists_url: 'https://api.github.com/users/vercel/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/vercel/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/vercel/subscriptions',
      organizations_url: 'https://api.github.com/users/vercel/orgs',
      repos_url: 'https://api.github.com/users/vercel/repos',
      events_url: 'https://api.github.com/users/vercel/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/vercel/received_events',
      type: 'Organization',
      site_admin: false
    },
    html_url: 'https://github.com/vercel/swr',
    description: 'React Hooks library for remote data fetching',
    fork: false,
    url: 'https://api.github.com/repos/vercel/swr',
    forks_url: 'https://api.github.com/repos/vercel/swr/forks',
    keys_url: 'https://api.github.com/repos/vercel/swr/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/vercel/swr/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/vercel/swr/teams',
    hooks_url: 'https://api.github.com/repos/vercel/swr/hooks',
    issue_events_url:
      'https://api.github.com/repos/vercel/swr/issues/events{/number}',
    events_url: 'https://api.github.com/repos/vercel/swr/events',
    assignees_url: 'https://api.github.com/repos/vercel/swr/assignees{/user}',
    branches_url: 'https://api.github.com/repos/vercel/swr/branches{/branch}',
    tags_url: 'https://api.github.com/repos/vercel/swr/tags',
    blobs_url: 'https://api.github.com/repos/vercel/swr/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/vercel/swr/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/vercel/swr/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/vercel/swr/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/vercel/swr/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/vercel/swr/languages',
    stargazers_url: 'https://api.github.com/repos/vercel/swr/stargazers',
    contributors_url: 'https://api.github.com/repos/vercel/swr/contributors',
    subscribers_url: 'https://api.github.com/repos/vercel/swr/subscribers',
    subscription_url: 'https://api.github.com/repos/vercel/swr/subscription',
    commits_url: 'https://api.github.com/repos/vercel/swr/commits{/sha}',
    git_commits_url:
      'https://api.github.com/repos/vercel/swr/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/vercel/swr/comments{/number}',
    issue_comment_url:
      'https://api.github.com/repos/vercel/swr/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/vercel/swr/contents/{+path}',
    compare_url:
      'https://api.github.com/repos/vercel/swr/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/vercel/swr/merges',
    archive_url:
      'https://api.github.com/repos/vercel/swr/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/vercel/swr/downloads',
    issues_url: 'https://api.github.com/repos/vercel/swr/issues{/number}',
    pulls_url: 'https://api.github.com/repos/vercel/swr/pulls{/number}',
    milestones_url:
      'https://api.github.com/repos/vercel/swr/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/vercel/swr/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/vercel/swr/labels{/name}',
    releases_url: 'https://api.github.com/repos/vercel/swr/releases{/id}',
    deployments_url: 'https://api.github.com/repos/vercel/swr/deployments',
    created_at: '2019-10-28T18:16:01Z',
    updated_at: '2020-12-22T10:39:44Z',
    pushed_at: '2020-12-21T01:52:44Z',
    git_url: 'git://github.com/vercel/swr.git',
    ssh_url: 'git@github.com:vercel/swr.git',
    clone_url: 'https://github.com/vercel/swr.git',
    svn_url: 'https://github.com/vercel/swr',
    homepage: 'https://swr.vercel.app',
    size: 1393,
    stargazers_count: 14818,
    watchers_count: 14818,
    language: 'TypeScript',
    has_issues: true,
    has_projects: false,
    has_downloads: true,
    has_wiki: false,
    has_pages: false,
    forks_count: 491,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 110,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz'
    },
    forks: 491,
    open_issues: 110,
    watchers: 14818,
    default_branch: 'master',
    temp_clone_token: null,
    organization: {
      login: 'vercel',
      id: 14985020,
      node_id: 'MDEyOk9yZ2FuaXphdGlvbjE0OTg1MDIw',
      avatar_url: 'https://avatars0.githubusercontent.com/u/14985020?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/vercel',
      html_url: 'https://github.com/vercel',
      followers_url: 'https://api.github.com/users/vercel/followers',
      following_url:
        'https://api.github.com/users/vercel/following{/other_user}',
      gists_url: 'https://api.github.com/users/vercel/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/vercel/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/vercel/subscriptions',
      organizations_url: 'https://api.github.com/users/vercel/orgs',
      repos_url: 'https://api.github.com/users/vercel/repos',
      events_url: 'https://api.github.com/users/vercel/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/vercel/received_events',
      type: 'Organization',
      site_admin: false
    },
    network_count: 491,
    subscribers_count: 126
  })
}
